### ISSUE TITLE
Another error : no such element exception

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-operetta-importer#14]
Cannot find coordinates
Exception in thread "Thread-4" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at ch.epfl.biop.operetta.OperettaManager.getBottomRightCoordinates(OperettaManager.java:1130)
	at ch.epfl.biop.operetta.OperettaManager.readSingleWell(OperettaManager.java:589)
	at ch.epfl.biop.operetta.OperettaManager.getWellImage(OperettaManager.java:439)
	at ch.epfl.biop.operetta.OperettaManager.process(OperettaManager.java:717)
	at ch.epfl.biop.operetta.commands.OperettaImporterInteractive.lambda$doProcess$5(OperettaImporterInteractive.java:435)
	at java.lang.Thread.run(Thread.java:748)

**Comment by NicoKiaru** [comment]
Related to this issue: https://forum.image.sc/t/operetta-reader-bug-positions-not-parsed-found/61818/3
