### ISSUE TITLE
NPE Exception

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-operetta-importer#9]
Observed with a dataset on WilyKat (which one @romainGuiet ?)

```
Well Well:0:5 stack 269 took 0.961 seconds
Exception in thread "Thread-15" java.lang.NullPointerException
	at ch.epfl.biop.operetta.OperettaManager.getUncalibratedCoordinates(OperettaManager.java:1004)
	at ch.epfl.biop.operetta.OperettaManager.writeWellPositionsFile(OperettaManager.java:816)
	at ch.epfl.biop.operetta.OperettaManager.process(OperettaManager.java:708)
	at ch.epfl.biop.operetta.commands.OperettaImporterInteractive.lambda$doProcess$5(OperettaImporterInteractive.java:443)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by romainGuiet** [comment]
this one : 
\InSilico_Channels_DL\20210316_Romain_acquisition_fixed_6chs\ExportData\Full-v2__2021-03-16T10_29_10-Measurement 1\Images\

**Comment by NicoKiaru** [comment]
Did you find a specific Field / Well failing ?

**Comment by NicoKiaru** [comment]
Ok I can reproduce, it fails on 
```
	 - Field WellSample:0:2:42 (43/45)
 -  Task 9 % completed. Elapsed time:0:00:53. Estimated remaining time: 0:08:04. Job done at around 10:30
	 - Field WellSample:0:2:43 (44/45)
 -  Task 9 % completed. Elapsed time:0:00:53. Estimated remaining time: 0:08:00. Job done at around 10:30
	 - Field WellSample:0:2:44 (45/45)
 -  Task 10 % completed. Elapsed time:0:00:53. Estimated remaining time: 0:07:57. Job done at around 10:30
```

**Comment by NicoKiaru** [comment]
The field 40 in R3-C6 makes it fail
